CREATE TABLE TBL_MEMBER_FILE(
    ID NUMBER CONSTRAINT PK_MEMBER_FILE PRIMARY KEY,
    MEMBER_ID NUMBER NOT NULL,
    CONSTRAINT FK_MEMBER_FILE_FILE FOREIGN KEY (ID)
    REFERENCES TBL_FILE(ID),
    CONSTRAINT FK_FILE_MEMBER FOREIGN KEY (MEMBER_ID)
    REFERENCES TBL_MEMBER(ID)
);

SELECT * FROM TBL_MEMBER_FILE;