CREATE SEQUENCE SEQ_REPLY;
CREATE TABLE TBL_REPLY(
    ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
    REPLY_CONTENT VARCHAR2(255) NOT NULL,
    REPLY_GROUP_ID NUMBER,
    REPLY_ORDER NUMBER DEFAULT 0,
    CREATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    MEMBER_ID NUMBER NOT NULL,
    POST_ID NUMBER NOT NULL,
    CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
    REFERENCES TBL_MEMBER(ID),
    CONSTRAINT FK_REPLY_POST FOREIGN KEY(POST_ID)
    REFERENCES TBL_POST(ID)
);
SELECT * FROM TBL_REPLY;
SELECT MAX(REPLY_ORDER) + 1 FROM TBL_REPLY WHERE REPLY_GROUP_ID=1;